init: fcitx5(local-share)

diff --git a/dot-zshrc b/dot-zshrc
--- a/dot-zshrc
+++ b/dot-zshrc
@@ -36,42 +36,38 @@ source $HOME/.config/zsh/prompt.zsh
 
 
 command_not_found_handler() {
-    local pkgs cmd="$@"
-    printf '\033[0;31m\033[1m==> ERROR: Command not found:\033[0m %s\n' "$cmd"
-    printf '\033[0m'
-    printf 'Checking for package.'
-    (
-        while true; do
-            ( sleep 0.1 && printf '.' )
-        done
-    ) &!
-    pkgs=(${(f)"$(pkgfile -b -v -- "$cmd" 2>/dev/null)"})
-    kill $!
-    echo
-    if [[ -n "$pkgs" ]]; then
-        printf 'The application %s is not installed. It may be found in the following AUR packages:\n' "$cmd"
-        printf '  %s\n' $pkgs[@]
-        setopt shwordsplit
-        pkg_array=($pkgs[@])
-        pkgname="${${(@s:/:)pkg_array}[2]}"
-        printf 'Do you want to Install AUR package %s? (y/N) ' $pkgname
-        if read -q "choice? "; then
-              echo
-              echo "Executing command: yay -S $pkgname"
-              yay -S $pkgname --noconfirm
-              echo " "
-              return
-            else
-              echo " "
-              return
-        fi
-    fi 1>&2
-    # printf 'Thinking.'
-    # ( sleep 0.1 && printf '.' ) &!
-    # ( sleep 0.1 && printf '.' ) &!
-    # ( sleep 0.1 && printf '.' ) &!
-    # eval $(thefuck --enable-experimental-instant-mode $@)
-
+    # local pkgs cmd="$@"
+    printf '\033[0;31m\033[1m==> ERROR: Command not found:\033[0m %s\n' "$@"
+    # printf '\033[0m'
+    # printf 'Checking for package.'
+    # (
+    #     while true; do
+    #         ( sleep 0.1 && printf '.' )
+    #     done
+    # ) &!
+    # pkgs=(${(f)"$(eix --only-names --pattern "^.*/${cmd}$" 2>/dev/null)"})
+    # kill $!
+    # echo
+    # if [[ -n "$pkgs" ]]; then
+    #     printf 'The application %s is not installed. It may be found in the following packages:\n' "$cmd"
+    #     printf '  %s\n' $pkgs[@]
+    #     if [[ ${#pkgs[@]} -eq 1 ]]; then
+    #         printf 'Do you want to Install package %s? (y/N) ' $pkgs[1]
+    #         if read -q "choice? "; then
+    #             echo
+    #             echo "Executing command: sudo emerge -av $pkgs[1]"
+    #             sudo emerge -av $pkgs[1]
+    #             echo " "
+    #             return
+    #         else
+    #             echo " "
+    #             return
+    #         fi
+    #     else
+    #         echo "Multiple packages found. Please use 'emerge -S $cmd' for more information."
+    #         return
+    #     fi
+    # fi 1>&2
     return 127
 }
 
@@ -90,7 +86,7 @@ command_not_found_handler() {
 
 precmd() {
     if [[ "$?" != 0 && "$?" != 127 && "$?" != 2 ]]; then
-        printf "\033[0;31m\033[1m==> ERROR: Command Faild to run.\n\n"
+        printf "\033[0;31m\033[1m==> ERROR: Command Faild to run."
         #printf 'Do you want to fuck? (y/N) '
         #if read -q "choice? "; then
         #    fuck $@
